In [10]:
# importing packages
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## **Loading, Understanding the data**

In [27]:
df = pd.read_csv("/kaggle/input/datasets/juhibhojani/house-price/house_prices.csv")
df.head()

,Index,Title,Description,Amount(in rupees),Price (in rupees),location,Carpet Area,Status,Floor,Transaction,...,facing,overlooking,Society,Bathroom,Balcony,Car Parking,Ownership,Super Area,Dimensions,Plot Area
0,0,1 BHK Ready to Occupy Flat for sale in Srushti...,"Bhiwandi, Thane has an attractive 1 BHK Flat f...",42 Lac,6000.0,thane,500 sqft,Ready to Move,10 out of 11,Resale,...,NaN,NaN,Srushti Siddhi Mangal Murti Complex,1,2,NaN,NaN,NaN,NaN,NaN
1,1,2 BHK Ready to Occupy Flat for sale in Dosti V...,One can find this stunning 2 BHK flat for sale...,98 Lac,13799.0,thane,473 sqft,Ready to Move,3 out of 22,Resale,...,East,Garden/Park,Dosti Vihar,2,NaN,1 Open,Freehold,NaN,NaN,NaN
2,2,2 BHK Ready to Occupy Flat for sale in Sunrise...,Up for immediate sale is a 2 BHK apartment in ...,1.40 Cr,17500.0,thane,779 sqft,Ready to Move,10 out of 29,Resale,...,East,Garden/Park,Sunrise by Kalpataru,2,NaN,1 Covered,Freehold,NaN,NaN,NaN
3,3,1 BHK Ready to Occupy Flat for sale Kasheli,This beautiful 1 BHK Flat is available for sal...,25 Lac,NaN,thane,530 sqft,Ready to Move,1 out of 3,Resale,...,NaN,NaN,NaN,1,1,NaN,NaN,NaN,NaN,NaN
4,4,2 BHK Ready to Occupy Flat for sale in TenX Ha...,"This lovely 2 BHK Flat in Pokhran Road, Thane ...",1.60 Cr,18824.0,thane,635 sqft,Ready to Move,20 out of 42,Resale,...,West,"Garden/Park, Main Road",TenX Habitat Raymond Realty,2,NaN,1 Covered,Co-operative Society,NaN,NaN,NaN

In [12]:
df.shape

(187531, 21)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 187531 entries, 0 to 187530
Data columns (total 21 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Index              187531 non-null  int64
 1   Title              187531 non-null  object
 2   Description        184508 non-null  object
 3   Amount(in rupees)  187531 non-null  object
 4   Price (in rupees)  169866 non-null  float64
 5   location           187531 non-null  object
 6   Carpet Area        106858 non-null  object
 7   Status             186916 non-null  object
 8   Floor              180454 non-null  object
 9   Transaction        187448 non-null  object
 10  Furnishing         184634 non-null  object
 11  facing             117298 non-null  object
 12  overlooking        106095 non-null  object
 13  Society            77853 non-null   object
 14  Bathroom           186703 non-null  object
 15  Balcony            138596 non-null  object
 16  Car Parking        84174 non-null   object
 17  Ownership          122014 non-null  object
 18  Super Area         79846 non-null   object
 19  Dimensions         0 non-null       float64
 20  Plot Area          0 non-null       float64
dtypes: float64(3), int64(1), object(17)
memory usage: 30.0+ MB

In [14]:
df.isnull().sum()

Index                     0
Title                     0
Description            3023
Amount(in rupees)         0
Price (in rupees)     17665
location                  0
Carpet Area           80673
Status                  615
Floor                  7077
Transaction              83
Furnishing             2897
facing                70233
overlooking           81436
Society              109678
Bathroom                828
Balcony               48935
Car Parking          103357
Ownership             65517
Super Area           107685
Dimensions           187531
Plot Area            187531
dtype: int64

In [15]:
print("num of duplicate rows:", df.duplicated().sum())

num of duplicate rows: 0

In [16]:
# seperate the numerical and categorical columns
df_cat = df.select_dtypes(['object'])
df_num = df.select_dtypes(['int64', 'float64'])

In [17]:
df_cat.describe()

,Title,Description,Amount(in rupees),location,Carpet Area,Status,Floor,Transaction,Furnishing,facing,overlooking,Society,Bathroom,Balcony,Car Parking,Ownership,Super Area
count,187531,184508,187531,187531,106858,186916,180454,187448,184634,117298,106095,77853,186703,138596,84174,122014,79846
unique,32446,65634,1561,81,2758,1,947,4,3,8,19,10376,11,11,229,4,2976
top,2 BHK Ready to Occupy Flat for sale in Divyasr...,Multistorey apartment is available for sale. I...,Call for Price,new-delhi,1000 sqft,Ready to Move,2 out of 4,Resale,Semi-Furnished,East,Main Road,Hamdam Apartment,2,2,1 Covered,Freehold,1100 sqft
freq,2106,2732,9684,27599,5285,186916,12433,144172,88318,54741,32193,1648,93007,51809,38754,112229,2599

In [18]:
df_num.describe(percentiles=[0.1, 0.25, 0.5, 0.75, 0.9])

               Index  Price (in rupees)  Dimensions  Plot Area
count  187531.000000       1.698660e+05         0.0        0.0
mean    93765.000000       7.583772e+03         NaN        NaN
std     54135.681003       2.724171e+04         NaN        NaN
min         0.000000       0.000000e+00         NaN        NaN
10%     18753.000000       3.434000e+03         NaN        NaN
25%     46882.500000       4.297000e+03         NaN        NaN
50%     93765.000000       6.034000e+03         NaN        NaN
75%    140647.500000       9.450000e+03         NaN        NaN
90%    168777.000000       1.271400e+04         NaN        NaN
max    187530.000000       6.700000e+06         NaN        NaN

## **Data Cleaning**

### **Renaming Columns**

In [29]:
df.rename(columns={
    'index': 'Index',
    'Amount(in rupees)': 'Amount',
    'Price (in rupees)': 'Price',
    'location': 'Location',
    'facing': 'Facing',
    'overlooking': 'Overlooking'
}, inplace=True)

df.rename(columns={col: col.replace(' ', '') for col in df.columns}, inplace=True)
df.head(2)

,Index,Title,Description,Amount,Price,Location,CarpetArea,Status,Floor,Transaction,...,Facing,Overlooking,Society,Bathroom,Balcony,CarParking,Ownership,SuperArea,Dimensions,PlotArea
0,0,1 BHK Ready to Occupy Flat for sale in Srushti...,"Bhiwandi, Thane has an attractive 1 BHK Flat f...",42 Lac,6000.0,thane,500 sqft,Ready to Move,10 out of 11,Resale,...,NaN,NaN,Srushti Siddhi Mangal Murti Complex,1,2,NaN,NaN,NaN,NaN,NaN
1,1,2 BHK Ready to Occupy Flat for sale in Dosti V...,One can find this stunning 2 BHK flat for sale...,98 Lac,13799.0,thane,473 sqft,Ready to Move,3 out of 22,Resale,...,East,Garden/Park,Dosti Vihar,2,NaN,1 Open,Freehold,NaN,NaN,NaN

### **Handling Missing Data**

In [32]:
# droping non-essential columns
df.drop(['Title', 'Description', 'Price', 'Society', 'Dimensions'], axis=1, inplace=True)

In [34]:
df.head()

,Index,Amount,Location,CarpetArea,Status,Floor,Transaction,Furnishing,Facing,Overlooking,Bathroom,Balcony,CarParking,Ownership,SuperArea,PlotArea
0,0,42 Lac,thane,500 sqft,Ready to Move,10 out of 11,Resale,Unfurnished,NaN,NaN,1,2,NaN,NaN,NaN,NaN
1,1,98 Lac,thane,473 sqft,Ready to Move,3 out of 22,Resale,Semi-Furnished,East,Garden/Park,2,NaN,1 Open,Freehold,NaN,NaN
2,2,1.40 Cr,thane,779 sqft,Ready to Move,10 out of 29,Resale,Unfurnished,East,Garden/Park,2,NaN,1 Covered,Freehold,NaN,NaN
3,3,25 Lac,thane,530 sqft,Ready to Move,1 out of 3,Resale,Unfurnished,NaN,NaN,1,1,NaN,NaN,NaN,NaN
4,4,1.60 Cr,thane,635 sqft,Ready to Move,20 out of 42,Resale,Unfurnished,West,"Garden/Park, Main Road",2,NaN,1 Covered,Co-operative Society,NaN,NaN

In [62]:
df.isnull().sum().sort_values(ascending=False)

PlotArea       187531
SuperArea      107685
CarpetArea      80673
Index               0
Status              0
Floor               0
Amount              0
Location            0
Furnishing          0
Transaction         0
Facing              0
Overlooking         0
Balcony             0
Bathroom            0
Ownership           0
CarParking          0
dtype: int64

In [61]:
# handling Bathroom, Balcony and CarParking
df['Bathroom'] = df['Bathroom'].fillna('0')
df['Balcony'] = df['Balcony'].fillna('0')
df['CarParking'] = df['CarParking'].fillna('0')

In [55]:
# handling Overlooking
df['Overlooking'] = df['Overlooking'].fillna('Nothing')

In [54]:
# handling Floor
df['Floor'] = df['Floor'].fillna('0 out of 0')

In [56]:
# handling Furnishing, Status and Transaction
df['Furnishing'] = df['Furnishing'].fillna(df['Furnishing'].mode()[0])
df['Status'] = df['Status'].fillna(df['Status'].mode()[0])
df['Transaction'] = df['Transaction'].fillna(df['Transaction'].mode()[0])

In [58]:
# handling Facing, Ownership
df['Facing'] = df['Facing'].fillna('No data')
df['Ownership'] = df['Ownership'].fillna('No data')

In [63]:
df.isnull().sum().sort_values(ascending=False)

PlotArea       187531
SuperArea      107685
CarpetArea      80673
Index               0
Status              0
Floor               0
Amount              0
Location            0
Furnishing          0
Transaction         0
Facing              0
Overlooking         0
Balcony             0
Bathroom            0
Ownership           0
CarParking          0
dtype: int64